name: Delete Stale Branches

on:
  workflow_dispatch:

jobs:
  delete-stale-branches:
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run script to delete stale branches
        run: |
          export GIT_TRACE=1 GIT_CURL_VERBOSE=1
          # Set the number of days after which a branch is considered stale
          DAYS=90

          # Get a list of all branches that have been merged with main
          MERGED_BRANCHES=$(git branch --merged main | grep -v '$main')

          # Loop through each merged branch
          for branch in $MERGED_BRANCHES
          do
            # Get the date of the last commit on the branch
            LAST_COMMIT_DATE=$(git log -1 --format=%ct $branch)

            # Calculate the number of days since the last commit
            DAYS_SINCE_LAST_COMMIT=$(( ($(date +%s) - $LAST_COMMIT_DATE) / 86400 ))

            # If the branch is stale, delete it
            if [ $DAYS_SINCE_LAST_COMMIT -gt $DAYS ]
            then
              git branch -D $branch
              git push origin --delete $branch
              echo "Deleted stale branch: $branch"
            fi
          done
        shell: bash
